openapi: "3.0.0"
info:
  version: 1.0.0
  title: Hach Zurich Docs
servers:
  - url: http://localhost:5000
security:
  - jwt: ['secret']
paths:
  /user:
    $ref: "./userapi.yml#user"
  '/user/{userId}':
    $ref: "./userapi.yml#user~1{userId}"
  '/user/{userId}/admin':
    $ref: "./userapi.yml#user~1{userId}~1admin"

  /city:
    $ref: "./cityapi.yml#city"
  '/city/{cityId}':
    $ref: "./cityapi.yml#city~1{cityId}"

  /itemTag:
    $ref: "./itemtagapi.yml#itemTag"
  '/itemTag/{itemTagId}':
    $ref: "./itemtagapi.yml#itemTag~1{itemTagId}"
  
  '/user/{userId}/need':
    $ref: "./userneedapi.yml#user~1{userId}~1need"
  '/user/{userId}/need/{needId}':
    $ref: "./userneedapi.yml#/user~1{userId}~1need~1{needId}"

  '/need':
    $ref: "./needapi.yml#need"

  '/user/{userId}/available':
    $ref: "./useravailableapi.yml#user~1{userId}~1available"
  '/user/{userId}/available/{availableId}':
    $ref: "./useravailableapi.yml#/user~1{userId}~1available~1{availableId}"

  '/available':
    $ref: "./availableapi.yml#available"

  '/me':
    $ref: "./meapi.yml#me"

  /auth/login:
    $ref: "./authapi.yml#login"
    
components:
  $ref: "./schemas.yml"




# Subresource considerations for a nested propery object of an entity:
# 1. If the propery needs different authorization access than the rest of the entity.
# 2. If the nested propery is a type of array.

# For each object type,
# 'additionalProperties: false' must be added
    